# Basic Information 
title: Zhihang Zhao
position: MSc Student
affiliation: The University of Warwick
affiliation_link: https://warwick.ac.uk/
email: Zhihang.Zhao@warwick.ac.uk

# Search Engine Optimization (SEO)
# The following information is used to improve the website traffic from search engines, e.g., Google.
keywords: zhihang zhao, zhao zhihang, zhaozhihang, zhihangzhao, zhihang
description: Zhihang Zhao is a postgraduate student at the University of Warwick, pursuing studies in Economics and International Financial Economics.
canonical: https://zhihangzhao.com

# The option is used to show the last update time.
enable_last_update: false

# Links 
# If you don't need one of them, you may delete the corresponding line.
# google_scholar: https://scholar.google.com/
cv_link: assets/files/cv-zhihangzhao.pdf
github_link: https://github.com/zigzaghumor
linkedin: https://www.linkedin.com/in/zhihangzhao/
twitter: https://twitter.com/zigzaghumor

# Images (e.g., your profile picture and your website's favicon) 
# "favicon" and "favicon_dark" are used for the light and dark modes, respectively. 
avatar: ./assets/img/avatar.gif
favicon: ./assets/img/favicon.png
favicon_dark: ./assets/img/favicon-dark.png

# Footnote
# You may use the option to disable the footnote, "Powered by Jekyll and Minimal Light theme."
enable_footnote: true

# The following files will be removed from the generated website.
exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - LICENSE
  - minimal-light.gemspec
